In [1]:
import pandas as pd
from pathlib import Path
import os


os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = "6,7"

In [106]:
DATA_DIR = Path("data", "ijcnlp_dailydialog", "train")
data = pd.read_csv(Path(DATA_DIR, "dialogues_train.txt"),  delimiter = "\n", names = ["dialogues"])

In [107]:
def seputterances(row):
    try:
        row = row.split("__eou__")
        row = row[:-1]
        return row
    except:
        return row

data["dialogues"] = data["dialogues"].apply(seputterances)

data

dialogues
0      [Say , Jim , how about going for a few beers a...
1      [Can you do push-ups ? ,  Of course I can . It...
2      [Can you study with the radio on ? ,  No , I l...
3      [Are you all right ? ,  I will be all right so...
4      [Hey John , nice skates . Are they new ? ,  Ye...
...                                                  ...
11113  [Hello , I bought a pen in your shop just befo...
11114  [Do you have any seats available ? ,  Yes . Th...
11115  [Uncle Ben , how did the Forbidden City get th...
11116  [May I help you , sir ? ,  I want a pair of lo...
11117  [Could I have the check , please ? ,  Okay . I...

[11118 rows x 1 columns]

In [108]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
print(tokenizer.eos_token)

<|endoftext|>


In [109]:
num_context = 3

utterance = []
history = []

for i in data.index:

    row = data["dialogues"][i]

    for idx  in range(len(row)):

        if idx != 0:
            
            utterance.append(row[idx])

            counter = 1
            _history = ""
            
            for k in range(idx-1, -1, -1):
                if counter <= num_context:
                    _history = _history + row[k]
                    counter +=1
                else:
                    break
                _history = _history + tokenizer.eos_token
            history.append(_history)
        else:
            continue

In [113]:
max_len = 32
tokenizer.add_special_tokens({'pad_token': '[PAD]'})

0

In [114]:
print(utterance[3].lower())
o = tokenizer.encode_plus(utterance[3].lower() + tokenizer.eos_token, max_length = max_len, padding= "max_length", truncation = True, return_tensors = "pt")
print(o, len(o["input_ids"][0]))
print(tokenizer.convert_ids_to_tokens(o["input_ids"][0]))

 i guess you are right.but what shall we do ? i don't feel like sitting at home . 
{'input_ids': tensor([[ 1312,  4724,   345,   389,   826,    13,  4360,   644,  2236,   356,
           466,  5633,  1312,   836,   470,  1254,   588,  5586,   379,  1363,
           764,   220, 50256, 50257, 50257, 50257, 50257, 50257, 50257, 50257,
         50257, 50257]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])} 32
['Ġi', 'Ġguess', 'Ġyou', 'Ġare', 'Ġright', '.', 'but', 'Ġwhat', 'Ġshall', 'Ġwe', 'Ġdo', 'Ġ?', 'Ġi', 'Ġdon', "'t", 'Ġfeel', 'Ġlike', 'Ġsitting', 'Ġat', 'Ġhome', 'Ġ.', 'Ġ', '<|endoftext|>', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']


In [115]:

print(history[3].lower())
v = tokenizer.encode_plus(history[3].lower(), max_length = max_len, truncation = True, padding= "max_length", return_tensors = "pt")
print(v, len(v["input_ids"][0]))
print(tokenizer.convert_ids_to_tokens(v["input_ids"][0]))

 do you really think so ? i don't . it will just make us fat and act silly . remember last time ? <|endoftext|> what do you mean ? it will help us to relax . <|endoftext|> you know that is tempting but is really not good for our fitness . <|endoftext|>
{'input_ids': tensor([[  466,   345,  1107,   892,   523,  5633,  1312,   836,   470,   764,
           340,   481,   655,   787,   514,  3735,   290,   719, 14397,   764,
          3505,   938,   640,  5633,   220, 50256,   644,   466,   345,  1612,
          5633,   340]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])} 32
['Ġdo', 'Ġyou', 'Ġreally', 'Ġthink', 'Ġso', 'Ġ?', 'Ġi', 'Ġdon', "'t", 'Ġ.', 'Ġit', 'Ġwill', 'Ġjust', 'Ġmake', 'Ġus', 'Ġfat', 'Ġand', 'Ġact', 'Ġsilly', 'Ġ.', 'Ġremember', 'Ġlast', 'Ġtime', 'Ġ?', 'Ġ', '<|endoftext|>', 'Ġwhat', 'Ġdo', 'Ġyou', 'Ġmean', 'Ġ?', 'Ġit']


In [98]:
o["input_ids"]

tensor([[ 1312,  4724,   345,   389,   826,    13,  4360,   644,  2236,   356,
           466,  5633,  1312,   836,   470,  1254,   588,  5586,   379,  1363,
           764,   220, 50256, 50257, 50257, 50257, 50257, 50257, 50257, 50257,
         50257, 50257]])

In [99]:
v["input_ids"]

tensor([[  466,   345,  1107,   892,   523,  5633,  1312,   836,   470,   764,
           340,   481,   655,   787,   514,  3735,   290,   719, 14397,   764,
          3505,   938,   640,  5633,   220, 50256,   644,   466,   345,  1612,
          5633,   340]])

In [105]:
import torch

torch.cat([o["input_ids"][0], v["input_ids"][0]], dim=0)

tensor([ 1312,  4724,   345,   389,   826,    13,  4360,   644,  2236,   356,
          466,  5633,  1312,   836,   470,  1254,   588,  5586,   379,  1363,
          764,   220, 50256, 50257, 50257, 50257, 50257, 50257, 50257, 50257,
        50257, 50257,   466,   345,  1107,   892,   523,  5633,  1312,   836,
          470,   764,   340,   481,   655,   787,   514,  3735,   290,   719,
        14397,   764,  3505,   938,   640,  5633,   220, 50256,   644,   466,
          345,  1612,  5633,   340])

tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1])

In [141]:
input_ids = []

attention_masks = []

labels = []

for i in range(len(utterance)):
    
    encoded_utterance = tokenizer.encode_plus(utterance[i].lower() + tokenizer.eos_token, max_length = max_len, padding= "max_length", truncation = True, return_tensors = "pt")
    
    encoded_history = tokenizer.encode_plus(history[i].lower(), max_length = max_len, truncation = True, padding= "max_length", return_tensors = "pt")
    
    ids = torch.cat([encoded_utterance["input_ids"][0], encoded_history["input_ids"][0]], dim=0)
    mask = torch.cat([encoded_utterance["attention_mask"][0], encoded_history["attention_mask"][0]], dim=0)
    label  = torch.cat([torch.full((max_len,), -100), torch.full((max_len,), 1)], dim = 0)

    input_ids.append(ids)
    attention_masks.append(mask)
    labels.append(label)
    break

print(input_ids, attention_masks, labels)

[tensor([  345,   760,   326,   318, 29850,   475,   318,  1107,   407,   922,
          329,   674, 13547,   764,   220, 50256, 50257, 50257, 50257, 50257,
        50257, 50257, 50257, 50257, 50257, 50257, 50257, 50257, 50257, 50257,
        50257, 50257, 16706,   837,   474,   320,   837,   703,   546,  1016,
          329,   257,  1178, 16800,   706,  8073,  5633,   220, 50256, 50257,
        50257, 50257, 50257, 50257, 50257, 50257, 50257, 50257, 50257, 50257,
        50257, 50257, 50257, 50257])] [tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])] [tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100,    1,    1,    1,    1,
           1,    1,    1,    1,  

In [117]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")

In [118]:
dataset = {"S1":[], "S2": []}


for i in range(len(data)):
    for j in range(len(data["dialogues"][i])):
        dataset["S1"].append(data["dialogues"][i][j])
        try:
            dataset["S2"].append(data["dialogues"][i][j+1])
        except:
            dataset["S2"].append(tokenizer.eos_token)

In [119]:
tokenizer.pad_token = tokenizer.eos_token

tokenized_dataset = tokenizer(
    dataset["S1"],
    dataset["S2"],
    padding=True,
    truncation=True,
    return_tensors = "pt"
)

tokenized_dataset

{'input_ids': tensor([[25515,   837,  5395,  ..., 50256, 50256, 50256],
        [  921,   760,   326,  ..., 50256, 50256, 50256],
        [ 1867,   466,   345,  ..., 50256, 50256, 50256],
        ...,
        [  314,   761,  2546,  ..., 50256, 50256, 50256],
        [23722,   314,   423,  ..., 50256, 50256, 50256],
        [16805,   764,   314,  ..., 50256, 50256, 50256]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [3]:
import pickle 

dataset = load_dataset('daily_dialog')

Using custom data configuration default
Reusing dataset daily_dialog (/home/cs18resch11003/.cache/huggingface/datasets/daily_dialog/default/1.0.0/1d0a58c7f2a4dab5ed9d01dbde8e55e0058e589ab81fce5c2df929ea810eabcd)
100%|██████████| 3/3 [00:00<00:00, 469.06it/s]


In [7]:
train_dataset = dataset["train"]
train_dataset

Dataset({
    features: ['dialog', 'act', 'emotion'],
    num_rows: 11118
})

In [8]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")

In [11]:
tokenizer.pad_token = tokenizer.eos_token

tokenized_dataset = tokenizer(
    train_dataset["dialog"][0],
    train_dataset["dialog"][0],
    padding=True,
    truncation=True,
    return_tensors = "pt"
)

In [39]:
tokenizer.pad_token = tokenizer.eos_token

def tokenize_function(example):
    print(example["dialog"][0])
    exit

In [40]:
tokenized_datasets = train_dataset.map(tokenize_function, batched=True)
tokenized_datasets

 50%|█████     | 6/12 [00:00<00:00, 28.05ba/s]

['Say , Jim , how about going for a few beers after dinner ? ', ' You know that is tempting but is really not good for our fitness . ', ' What do you mean ? It will help us to relax . ', " Do you really think so ? I don't . It will just make us fat and act silly . Remember last time ? ", " I guess you are right.But what shall we do ? I don't feel like sitting at home . ", ' I suggest a walk over to the gym where we can play singsong and meet some of our friends . ', " That's a good idea . I hear Mary and Sally often go there to play pingpong.Perhaps we can make a foursome with them . ", ' Sounds great to me ! If they are willing , we could ask them to go dancing with us.That is excellent exercise and fun , too . ', " Good.Let ' s go now . ", ' All right . ']
['Great party , isn ’ t it ? ', ' Yeah , really . ', ' By the way , my name is Liu Wei . ', ' Hi , I ’ m Susan Marshall , You can call me Susan.Nice to meet you . ', ' What do you do , Susan ? ', ' Well , I ’ m a college student.Ho

100%|██████████| 12/12 [00:00<00:00, 30.39ba/s]

['Do you have this design with only one breast pocket ? ', ' Let me see.Oh , we have the design but not the same color as this one . ', " It's a pity . I'm afraid that's too loud for me.Thank you . ", " You're welcome . "]
['I have been getting headaches almost every day lately . ', ' Have you just started getting a lot of headaches ? ', ' I never had very many headaches before , but the last few weeks I have been getting a lot of them . ', ' Have you had any unusually stressful situations in your life lately ? ', ' My mother just passed away last Tuesday . ', ' I ’ m sorry . How about sleep ? Are you getting enough rest ? ', ' I have been working really hard , and sleep has not been a priority . ', ' Have you bumped your head or fallen lately ? ', ' No , I haven ’ t hit my head . ', ' I am going to send you to a neurologist for a few tests . ']
['May I help you ? Miss ! ', " Yes . I'd like to look at lipstick and eye shadow . ", ' What color set do you prefer ? ', ' Well , brown . ', 

Dataset({
    features: ['dialog', 'act', 'emotion'],
    num_rows: 11118
})

In [123]:
import os.path
os.path.isfile(Path("data", "inturn_conversations.pkl")) 

True

In [105]:
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

In [108]:
import torch
from transformers import AdamW
from transformers import get_scheduler

optimizer = AdamW(model.parameters(), lr=5e-5)

num_epochs = 3

num_batch = 2

num_training_steps = int(num_epochs * len(tokenized_dataset["input_ids"])/4)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model.to(device)

print(num_training_steps, device)

77235 cuda


In [109]:
from tqdm.auto import tqdm

progress_bar = tqdm(range(num_training_steps))

model.train()

for epoch in range(num_epochs):
    for i in range(len(tokenized_dataset["input_ids"])):
        inputs= {}

        ids = tokenized_dataset["input_ids"][:num_batch]
        mask = tokenized_dataset["attention_mask"][:num_batch]

        inputs["input_ids"] = ids.to(device)
        inputs["attention_mask"] = mask.to(device)

        outputs = model(**inputs, labels = inputs["input_ids"])
        print(outputs)

        loss = outputs.loss
        
        loss.backward()
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        
        progress_bar.update(1)
        
        break


  0%|          | 0/77235 [00:10<?, ?it/s]


RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.90 GiB total capacity; 4.54 GiB already allocated; 23.75 MiB free; 4.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF